from datetime import datetime, timedelta

from airflow import DAG
from airflow.operators.python import PythonOperator

from utils.extract import extract_tft_matches_by_puuid


default_args = {
    "owner": "airflow",
    "depends_on_past": False,
    "retries": 2,
    "retry_delay": timedelta(minutes=5),
}


with DAG(
    dag_id="riot_tft_match_entries_by_puuid",
    description="Extract TFT match entries by PUUID from Riot API",
    default_args=default_args,
    start_date=datetime(2026, 1, 1),
    schedule_interval=None,
    catchup=False,
    tags=["riot", "extract", "tft"],
) as dag:
    PythonOperator(
        task_id="extract_tft_matches_by_puuid",
        python_callable=extract_tft_matches_by_puuid,
        op_kwargs={
            "puuid_file": "/opt/airflow/data/raw/tft/puuids/tft_challenger_20260206_231109.json",  # Harcoded for now, but should be generated by another DAG that extracts PUUIDs from the challenger leaderboard
        },
    )
